language: python

install:
  - if [[ $TEST_SUITE == "static" ]]; then pip install -e . [static]; fi
  - if [[ $TEST_SUITE == "unit" ]]; then pip install -e . [unit]; fi

env:
  - TEST_SUITE=static
  - TEST_SUITE=unit

script:
  - if [[ $TEST_SUITE == "static" ]]; then flake8 --ignore E501,F; fi
  - if [[ $TEST_SUITE == "unit" ]]; then pytest --cov=./ecodse_funtime_alpha; fi

after_success:
  - codecov
